name: "Test custom action"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
      - unlabeled
  pull_request_review:
    types:
      - submitted
  push:
    branches:
      - main

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test action
    runs-on: ${{ vars.RUNNER }}
    steps:
      - uses: arghpy/get-pr-status@collect_info
